### ISSUE TITLE
readLine vs Scanner

### ISSUE THREAD

**Issue by kozlyakov-m** [PetrSed/GoodLine-Kafedra-se-test#4]
в стандартной библиотеке Kotlin есть readLine(), зачем использовать Java-вариант?

https://github.com/PetrSed/GoodLine-Kafedra-se-test/blob/6899f6507c867c96fbbbe6707b3157b035a49f79/6.kt#L6

**Comment by PetrSed** [comment]
Глянь коммиты, там два варианта решения)
java.Scanner сказали использовать в нашем телеграм чате
